[package]
name = "kls"
version = "0.0.1"
edition = "2021"
description = "Reserved"
authors = ["kinire98"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
